language: python
python:
  - 2.7

install: pip install pdfjinja
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq tk8.6-dev python-tk tcl8.6-dev
  - sudo apt-get install -qq libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev
  - sudo apt-get install -qq pdftk libmagickwand-dev
script: python tests.py
