language: python
python:
  - 2.7
sudo: false
install: pip install pdfjinja
addons:
  apt:
    packages:
    - tcl8.6-dev
    - tk8.6-dev
    - python-tk
    - libtiff5-dev
    - libjpeg8-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - libmagickwand-dev
    - pdftk
script: python tests.py
